### ISSUE TITLE
用新版本主题覆盖后出错，typecho主题选择界面加载不出所有主题

### ISSUE THREAD

**Issue by PermanentKing** [AlanDecode/Typecho-Theme-VOID#36]
**问题描述**
下载3.4.0和3.3.0版本主题并覆盖3.0.0版本主题后，博客网页空白，在admin界面，进行主题选择的时候所有界面均显示不出来，删去VOID主题文件夹后即可正常加载其他主题选项并启用，且重新移入3.0.0版本VOID主题后可正常使用。

**配置与环境**
* PHP 版本：php-5.4
* MySQL 版本：mysql 5.5
* Typecho 版本：1.1
* 主题版本：3.4.0, 3.3.0
* 插件版本：1.2

**截图（若有）**
<img width="980" alt="屏幕快照2" src="https://user-images.githubusercontent.com/26197624/76680707-cb5e4f00-6625-11ea-81b3-a9568f332de4.png">
<img width="478" alt="屏幕快照1" src="https://user-images.githubusercontent.com/26197624/76680772-7969f900-6626-11ea-8171-fd72e59273af.png">

**补充信息**
将版本更换回3.0.0版本后，启用后报错显示：
Duplicate entry 'theme:VOID-0' for key 'PRIMARY'exception 'Typecho_Db_Query_Exception' with message 'Duplicate entry 'theme:VOID-0' for key 'PRIMARY'' in /www/wwwroot/lostking.cn/var/Typecho/Db/Adapter/Mysql.php:88
Stack trace:
#0 /www/wwwroot/lostking.cn/var/Typecho/Db.php(354): Typecho_Db_Adapter_Mysql->query('INSERT INTO typ...', Resource id #27, 2, 'INSERT')
#1 /www/wwwroot/lostking.cn/var/Widget/Abstract/Options.php(56): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /www/wwwroot/lostking.cn/var/Widget/Themes/Edit.php(61): Widget_Abstract_Options->insert(Array)
#3 /www/wwwroot/lostking.cn/var/Widget/Themes/Edit.php(173): Widget_Themes_Edit->changeTheme('VOID')
#4 /www/wwwroot/lostking.cn/var/Widget/Do.php(82): Widget_Themes_Edit->action()
#5 /www/wwwroot/lostking.cn/var/Typecho/Widget.php(221): Widget_Do->execute()
#6 /www/wwwroot/lostking.cn/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#7 /www/wwwroot/lostking.cn/index.php(23): Typecho_Router::dispatch()
#8 {main}

刷新后便未出现问题

**Comment by PermanentKing** [comment]
已解决，是php版本过低的原因
