### ISSUE TITLE
启用配套插件时报Database Query Error

### ISSUE THREAD

**Issue by sirliu** [AlanDecode/Typecho-Theme-VOID#66]
**实际行为描述**
启用配套插件时报Database Query Error

**应有的行为**

**复现步骤**

**配置与环境**
* 出错页面链接：启用配套插件时报Database Query Error
* PHP 版本：7.2.18
* MySQL 版本：使用的sqlite3，未使用mysql
* Typecho 版本：由 Typecho 强力驱动, 版本 1.2 (19.05.09)
* 主题版本： 3.5.1
* 插件版本：1.2

**截图（若有）**

**补充信息**

开启debug后的报错信息如下：
```
SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1 near "SHOW": syntax error in /app/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /app/var/Typecho/Db.php(368): Typecho_Db_Adapter_Pdo->query('SHOW COLUMNS FR...', Object(PDO), 1, 'SELECT', NULL)
#1 /app/var/Typecho/Db.php(398): Typecho_Db->query('SHOW COLUMNS FR...', 1)
#2 /data/plugins/VOID/Plugin.php(23): Typecho_Db->fetchAll('SHOW COLUMNS FR...')
#3 /data/plugins/VOID/Plugin.php(68): VOID_Plugin::hasColumn('typecho_content...', 'wordCount')
#4 /app/var/Widget/Plugins/Edit.php(102): VOID_Plugin::activate()
#5 /app/var/Widget/Plugins/Edit.php(308): Widget_Plugins_Edit->activate('VOID')
#6 /app/var/Widget/Do.php(82): Widget_Plugins_Edit->action()
#7 /app/var/Typecho/Widget.php(221): Widget_Do->execute()
#8 /app/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#9 /app/index.php(23): Typecho_Router::dispatch()
#10 {main}
```

**Comment by AlanDecode** [comment]
目前不支持sqlite3

**Comment by badcodebuilder** [comment]
我用postgresql也不持支，不如在页面上写好仅支持MySQL
